export enum MainChannel {
  OPEN_MSA_LOGIN_WINDOW = "OPEN_MSA_LOGIN_WINDOW",
  GET_SELECTED_ACCOUNT = "GET_SELECTED_ACCOUNT",
  GET_ACCOUNTS = "GET_ACCOUNTS",
  RUN_MINECRAFT = "RUN_MINECRAFT",
}

export enum RendererChannel {
  CLOSE_MSA_LOGIN_WINDOW = "CLOSE_MSA_LOGIN_WINDOW",
  FETCH_MS_ACCOUNT = "FETCH_MS_ACCOUNT",
  RUN_MINECRAFT_EMITTER = "RUN_MINECRAFT_EMITTER",
}
